import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Search, Send, Sparkles } from "lucide-react";
import { useState, type FormEvent } from "react";
import { toast } from "sonner";
import poster from "@/assets/smaa-poster.jpg";
import posterHuman from "@/assets/smaa-poster-human.jpg";
import character from "@/assets/smaa-character.jpg";
import { AgentActivity, EmptyState, ErrorState, LoadingState, PageHeader } from "@/components/smaa/system";
import { AssetCard } from "@/components/smaa/assets";
import { Button } from "@/components/ui/button";
import { assetsApi, assistantApi, brandApi, integrationsApi, publishingApi, workspaceApi } from "@/lib/api/services";

const createOptions=[
  {title:"Poster",copy:"Create a brand-aware social poster.",to:"/create/poster",image:poster,type:"Visual campaign"},
  {title:"Poster + Human",copy:"Build a social visual with a realistic human subject.",to:"/create/poster-human",image:posterHuman,type:"Human-led campaign"},
  {title:"Human Character",copy:"Create a reusable character for future campaigns.",to:"/create/character",image:character,type:"Reusable asset"},
] as const;
export function CreateCards(){return <div className="create-grid">{createOptions.map((item)=><Link key={item.to} to={item.to} className="create-card"><img src={item.image} alt="" width={1200} height={1504} loading="lazy"/><div className="create-card-content"><p className="eyebrow">{item.type}</p><h3>{item.title}</h3><p>{item.copy}</p></div><span className="arrow"><ArrowRight/></span></Link>)}</div>}

export function DashboardScreen(){const [prompt,setPrompt]=useState("");const workspace=useQuery({queryKey:["workspace"],queryFn:workspaceApi.get,retry:false});const assets=useQuery({queryKey:["assets","dashboard"],queryFn:()=>assetsApi.list("?limit=8"),retry:false});const send=useMutation({mutationFn:assistantApi.send,onSuccess:()=>{toast.success("Request sent to SMAA");setPrompt("")},onError:(e:Error)=>toast.error(e.message)});const events=assets.data?.assets.find(a=>a.status==="generating")?.events;const review=assets.data?.assets.filter(a=>a.status==="ready")??[];const recent=assets.data?.assets??[];const name=workspace.data?.name??"Your workspace";
  return <div className="page-wrap"><section className="command-hero"><div className="command-composer panel"><div><p className="eyebrow">Good morning · {name}</p><h1>Your AI marketing teammate is ready.</h1><p>Assign the next piece of work. SMAA will use the context your team has connected.</p></div><form className="composer-box" onSubmit={(e)=>{e.preventDefault();if(prompt.trim())send.mutate(prompt)}}><textarea aria-label="What should SMAA work on?" placeholder="Create a recruitment campaign for our September intake." value={prompt} onChange={e=>setPrompt(e.target.value)}/><Button type="submit" disabled={!prompt.trim()||send.isPending}>{send.isPending?"Sending…":"Create"}<ArrowRight/></Button></form></div><AgentActivity events={events}/></section>
  <div className="section-heading"><div><h2>Needs your decision</h2><p>{review.length?`${review.length} ${review.length===1?"asset is":"assets are"} waiting for review`:"Review-ready work will appear here."}</p></div>{review.length?<Button asChild variant="outline"><Link to="/library" search={{tab:"ready"} as never}>Review now</Link></Button>:null}</div>{assets.isLoading?<LoadingState label="Checking review queue"/>:assets.isError?<ErrorState message={(assets.error as Error).message} retry={()=>assets.refetch()}/>:review.length?<div className="asset-grid">{review.slice(0,3).map(a=><AssetCard key={a.id} asset={a}/>)}</div>:<EmptyState title="Nothing needs your decision" message="New generations will appear here when they are ready for human review."/>}
  <div className="section-heading"><div><h2>Quick create</h2><p>Start with one of SMAA’s focused creative workflows.</p></div></div><CreateCards/>
  <div className="section-heading"><div><h2>Recent work</h2><p>The latest activity across your workspace.</p></div><Button asChild variant="ghost"><Link to="/library">View library<ArrowRight/></Link></Button></div>{assets.isLoading?<LoadingState/>:recent.length?<div className="asset-grid">{recent.slice(0,3).map(a=><AssetCard key={a.id} asset={a}/>)}</div>:<EmptyState title="No creations yet" message="Create your first brand-aware asset to begin your library." action={<Button asChild><Link to="/create/poster">Create poster</Link></Button>}/>}</div>}

export function CreateHubScreen(){return <div className="page-wrap"><PageHeader eyebrow="Create" title="What should SMAA create?" description="Assign focused creative work while your brand context stays in the loop."/><CreateCards/></div>}

export function ReviewScreen(){const q=useQuery({queryKey:["assets","ready"],queryFn:()=>assetsApi.list("?status=ready"),retry:false});return <div className="page-wrap"><PageHeader eyebrow="Human review" title="Needs your decision" description="Approve, refine or reject work that SMAA has prepared for your team."/>{q.isLoading?<LoadingState label="Checking review queue"/>:q.isError?<ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/>:(q.data?.assets??[]).length?<div className="asset-grid">{(q.data?.assets??[]).map(a=><AssetCard key={a.id} asset={a}/>)}</div>:<EmptyState title="Nothing is waiting for review" message="Ready assets will appear here when they need a human decision."/>}</div>}

export function LibraryScreen(){const [tab,setTab]=useState("all");const [search,setSearch]=useState("");const q=useQuery({queryKey:["assets",tab,search],queryFn:()=>assetsApi.list(`?status=${encodeURIComponent(tab)}&search=${encodeURIComponent(search)}`),retry:false});return <div className="page-wrap"><PageHeader eyebrow="Creative library" title="Work, in one place." description="Review every asset, decision and publishing state across the workspace."/><div className="toolbar"><div className="search-box"><Search/><input aria-label="Search creations" placeholder="Search creations…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="tabs-row" role="tablist">{["all","posters","poster + human","characters","approved","rejected","published"].map(x=><button className="tab-pill" data-active={tab===x} onClick={()=>setTab(x)} role="tab" aria-selected={tab===x} key={x}>{x.charAt(0).toUpperCase()+x.slice(1)}</button>)}</div><div className="mt-5">{q.isLoading?<LoadingState label="Loading creations"/>:q.isError?<ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/>:(q.data?.assets??[]).length?<div className="asset-grid">{(q.data?.assets??[]).map(a=><AssetCard key={a.id} asset={a}/>)}</div>:<EmptyState title="No creations yet" message="Create your first brand-aware asset." action={<Button asChild><Link to="/create/poster">Create poster</Link></Button>}/>}</div></div>}

export function BrandScreen(){const q=useQuery({queryKey:["brand"],queryFn:brandApi.get,retry:false});const refresh=useMutation({mutationFn:brandApi.refresh,onSuccess:()=>toast.success("Brand refresh started"),onError:(e:Error)=>toast.error(e.message)});return <div className="page-wrap"><PageHeader eyebrow="Brand Memory" title="Your brand memory" description="SMAA uses your digital presence, team decisions and approved content to create work that stays aligned." action={<Button onClick={()=>refresh.mutate()} disabled={refresh.isPending}><Sparkles/>{refresh.isPending?"Refreshing…":"Refresh knowledge"}</Button>}/>{q.isLoading?<LoadingState label="Loading brand memory"/>:q.isError?<ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/>:<><section className="panel form-panel"><div className="section-heading mt-0"><div><h2>Brand DNA</h2><p>What SMAA understands about your voice and identity.</p></div></div><div className="grid gap-8 md:grid-cols-2">{Object.entries({"Brand voice":q.data?.voice,"Audience":q.data?.audience,"Messaging":q.data?.messaging,"Visual identity":q.data?.visualIdentity}).map(([key,val])=><div key={key}><h3 className="text-sm font-semibold mb-3">{key}</h3>{val?.length?<div className="tag-list">{val.map(x=><span className="tag" key={x}>{x}</span>)}</div>:<p className="text-sm text-muted-foreground">No confirmed context yet.</p>}</div>)}</div></section><div className="section-heading"><div><h2>Knowledge sources</h2><p>Connected sources that shape your brand context.</p></div></div>{q.data?.sources?.length?<div className="integration-grid">{q.data.sources.map(s=><article className="panel integration-card" key={s.id}><span className="integration-icon">{s.name.slice(0,1)}</span><div><h3>{s.name}</h3><p>{s.connected?`Connected${s.count?` · ${s.count} analyzed`:""}`:"Not connected"}</p></div></article>)}</div>:<EmptyState title="No knowledge sources connected" message="Connect brand sources in Integrations to help SMAA learn your context."/>}</>}</div>}

export function IntegrationsScreen(){const q=useQuery({queryKey:["integrations"],queryFn:integrationsApi.list,retry:false});return <div className="page-wrap"><PageHeader eyebrow="Connections" title="Integrations" description="Bring SMAA into the tools and channels where your marketing team already works."/>{q.isLoading?<LoadingState/>:q.isError?<><ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/><StaticIntegrationNames/></>:(q.data?.integrations??[]).length?<div className="integration-grid">{(q.data?.integrations??[]).map(i=><article className="panel integration-card" key={i.id}><span className="integration-icon">{i.name[0]}</span><div><h3>{i.name}</h3><p>{i.status.replaceAll("_"," ")}{i.workspaceName?` · ${i.workspaceName}`:""}</p></div></article>)}</div>:<StaticIntegrationNames/>}</div>}
function StaticIntegrationNames(){return <div className="integration-grid mt-5">{["Slack","Instagram","Website","LinkedIn","TikTok","YouTube","Facebook","X"].map(name=><article className="panel integration-card" key={name}><span className="integration-icon">{name[0]}</span><div><h3>{name}</h3><p>Status unavailable until the API is connected.</p></div></article>)}</div>}

export function PublishingScreen(){const [tab,setTab]=useState("ready");const q=useQuery({queryKey:["publishing"],queryFn:publishingApi.list,retry:false});return <div className="page-wrap"><PageHeader eyebrow="Publishing" title="Move approved work forward." description="Review destination, caption and timing before anything goes live."/><div className="tabs-row mb-5">{["ready","scheduled","published","failed"].map(x=><button className="tab-pill" data-active={tab===x} onClick={()=>setTab(x)} key={x}>{x.charAt(0).toUpperCase()+x.slice(1)}</button>)}</div>{q.isLoading?<LoadingState/>:q.isError?<ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/>:(q.data?.items??[]).filter(i=>i.status===tab).length?<div className="asset-grid">{(q.data?.items??[]).filter(i=>i.status===tab).map(i=><AssetCard key={i.id} asset={i.asset}/>)}</div>:<EmptyState title="Nothing is ready to publish" message="Approve content from your Library first." action={<Button asChild variant="outline"><Link to="/library">Open library</Link></Button>}/>}</div>}

export function AssistantScreen(){const [message,setMessage]=useState("");const send=useMutation({mutationFn:assistantApi.send,onSuccess:()=>{toast.success("SMAA received your request");setMessage("")},onError:(e:Error)=>toast.error(e.message)});const submit=(e:FormEvent)=>{e.preventDefault();if(message.trim())send.mutate(message)};return <div className="page-wrap"><PageHeader eyebrow="SMAA Assistant" title="Work with your marketing teammate." description="Ask for creative work, campaign thinking or help preparing an approval."/><div className="assistant-layout"><section className="panel conversation"><div className="conversation-empty"><div><span className="agent-mark mx-auto"><Sparkles/></span><h2 className="mt-4 text-xl font-semibold">What should we work on?</h2><p className="mt-2 text-sm text-muted-foreground">SMAA will use available brand context and return real work objects here.</p><div className="assistant-suggestions"><Button variant="outline" size="sm" onClick={()=>setMessage("Create a social poster")}>Poster</Button><Button variant="outline" size="sm" onClick={()=>setMessage("Create a poster featuring a human")}>Poster + Human</Button><Button variant="outline" size="sm" onClick={()=>setMessage("Create a campaign character")}>Character</Button></div></div></div><form className="conversation-composer panel" onSubmit={submit}><textarea aria-label="Message SMAA" placeholder="Ask SMAA what to work on…" value={message} onChange={e=>setMessage(e.target.value)}/><div className="flex justify-end"><Button type="submit" disabled={!message.trim()||send.isPending}>{send.isPending?"Sending…":"Send"}<Send/></Button></div></form></section><AgentActivity/></div></div>}

export function SettingsScreen(){return <div className="page-wrap"><PageHeader eyebrow="Workspace" title="Settings" description="Manage the essentials without losing focus on the work."/><div className="settings-list">{[["Profile","Your personal details and preferences"],["Workspace","Team identity and workspace details"],["Generation preferences","Defaults used when creating new work"],["Notifications","Choose which updates need your attention"],["Integrations","Manage connected tools and channels"]].map(([a,b])=><div className="settings-row" key={a}><h3>{a}</h3><p>{b}</p><Button variant="ghost" size="icon" aria-label={`Open ${a}`}><ArrowRight/></Button></div>)}</div></div>}
