import { useQuery } from "@tanstack/react-query";
import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Search } from "lucide-react";
import { useState } from "react";
import poster from "@/assets/smaa-poster.jpg";
import posterHuman from "@/assets/smaa-poster-human.jpg";
import character from "@/assets/smaa-character.jpg";
import { AgentActivity, EmptyState, ErrorState, LoadingState, PageHeader } from "@/components/smaa/system";
import { AssetCard } from "@/components/smaa/assets";
import { Button } from "@/components/ui/button";
import { assetsApi, brandApi, workspaceApi } from "@/lib/api/services";

const createOptions=[
  {title:"Poster",copy:"Create a brand-aware social poster.",to:"/create/poster",image:poster,type:"Visual campaign"},
  {title:"Poster + Human",copy:"Build a social visual with a realistic human subject.",to:"/create/poster-human",image:posterHuman,type:"Human-led campaign"},
  {title:"Human Character",copy:"Create a reusable character for future campaigns.",to:"/create/character",image:character,type:"Reusable asset"},
] as const;
export function CreateCards(){return <div className="create-grid">{createOptions.map((item)=><Link key={item.to} to={item.to} className="create-card"><img src={item.image} alt="" width={1200} height={1504} loading="lazy"/><div className="create-card-content"><p className="eyebrow">{item.type}</p><h3>{item.title}</h3><p>{item.copy}</p></div><span className="arrow"><ArrowRight/></span></Link>)}</div>}

export function DashboardScreen(){const [prompt,setPrompt]=useState("");const navigate=useNavigate();const workspace=useQuery({queryKey:["workspace"],queryFn:workspaceApi.get,retry:false});const assets=useQuery({queryKey:["assets","dashboard"],queryFn:()=>assetsApi.list("?limit=8"),retry:false});const events=assets.data?.assets.find(a=>a.status==="generating")?.events;const review=assets.data?.assets.filter(a=>a.status==="ready")??[];const recent=assets.data?.assets??[];const name=workspace.data?.name??"Your workspace";
  // The composer starts real work: it carries the brief into the poster generator instead of posting to a chat endpoint that does not exist.
  return <div className="page-wrap"><section className="command-hero"><div className="command-composer panel"><div><p className="eyebrow">Good morning · {name}</p><h1>Your AI marketing teammate is ready.</h1><p>Describe the next piece of work. SMAA opens the poster generator with your brief.</p></div><form className="composer-box" onSubmit={(e)=>{e.preventDefault();if(prompt.trim())void navigate({to:"/create/poster",search:{prompt:prompt.trim()}})}}><textarea aria-label="What should SMAA work on?" placeholder="Create a recruitment campaign for our September intake." value={prompt} onChange={e=>setPrompt(e.target.value)}/><Button type="submit" disabled={!prompt.trim()}>Create<ArrowRight/></Button></form></div><AgentActivity events={events}/></section>
  <div className="section-heading"><div><h2>Needs your decision</h2><p>{review.length?`${review.length} ${review.length===1?"asset is":"assets are"} waiting for review`:"Review-ready work will appear here."}</p></div>{review.length?<Button asChild variant="outline"><Link to="/review">Review now</Link></Button>:null}</div>{assets.isLoading?<LoadingState label="Checking review queue"/>:assets.isError?<ErrorState message={(assets.error as Error).message} retry={()=>assets.refetch()}/>:review.length?<div className="asset-grid">{review.slice(0,3).map(a=><AssetCard key={a.id} asset={a}/>)}</div>:<EmptyState title="Nothing needs your decision" message="New generations will appear here when they are ready for human review."/>}
  <div className="section-heading"><div><h2>Quick create</h2><p>Start with one of SMAA’s focused creative workflows.</p></div></div><CreateCards/>
  <div className="section-heading"><div><h2>Recent work</h2><p>The latest activity across your workspace.</p></div><Button asChild variant="ghost"><Link to="/library">View library<ArrowRight/></Link></Button></div>{assets.isLoading?<LoadingState/>:recent.length?<div className="asset-grid">{recent.slice(0,3).map(a=><AssetCard key={a.id} asset={a}/>)}</div>:<EmptyState title="No creations yet" message="Create your first brand-aware asset to begin your library." action={<Button asChild><Link to="/create/poster">Create poster</Link></Button>}/>}</div>}

export function CreateHubScreen(){return <div className="page-wrap"><PageHeader eyebrow="Create" title="What should SMAA create?" description="Assign focused creative work while your brand context stays in the loop."/><CreateCards/></div>}

export function ReviewScreen(){const q=useQuery({queryKey:["assets","ready"],queryFn:()=>assetsApi.list("?status=ready"),retry:false});return <div className="page-wrap"><PageHeader eyebrow="Human review" title="Needs your decision" description="Keep the work that is good — saving writes it into your shared assets library — or refine a poster until it is right."/>{q.isLoading?<LoadingState label="Checking review queue"/>:q.isError?<ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/>:(q.data?.assets??[]).length?<div className="asset-grid">{(q.data?.assets??[]).map(a=><AssetCard key={a.id} asset={a}/>)}</div>:<EmptyState title="Nothing is waiting for review" message="Ready assets will appear here when they need a human decision."/>}</div>}

// Only tabs the backend can actually answer. There is no rejected or published state anywhere in this build.
const LIBRARY_TABS=["all","posters","poster + human","characters","approved"];
export function LibraryScreen(){const [tab,setTab]=useState("all");const [search,setSearch]=useState("");const q=useQuery({queryKey:["assets",tab,search],queryFn:()=>assetsApi.list(`?status=${encodeURIComponent(tab)}&search=${encodeURIComponent(search)}`),retry:false});return <div className="page-wrap"><PageHeader eyebrow="Creative library" title="Work, in one place." description="Every generation from the last 72 hours, newest first."/><div className="toolbar"><div className="search-box"><Search/><input aria-label="Search creations" placeholder="Search creations…" value={search} onChange={e=>setSearch(e.target.value)}/></div></div><div className="tabs-row" role="tablist">{LIBRARY_TABS.map(x=><button className="tab-pill" data-active={tab===x} onClick={()=>setTab(x)} role="tab" aria-selected={tab===x} key={x}>{x.charAt(0).toUpperCase()+x.slice(1)}</button>)}</div><div className="mt-5">{q.isLoading?<LoadingState label="Loading creations"/>:q.isError?<ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/>:(q.data?.assets??[]).length?<div className="asset-grid">{(q.data?.assets??[]).map(a=><AssetCard key={a.id} asset={a}/>)}</div>:<EmptyState title="No creations yet" message="Create your first brand-aware asset." action={<Button asChild><Link to="/create/poster">Create poster</Link></Button>}/>}</div></div>}

export function BrandScreen(){const q=useQuery({queryKey:["brand"],queryFn:brandApi.get,retry:false});return <div className="page-wrap"><PageHeader eyebrow="Brand Memory" title="Your brand memory" description="SMAA uses your digital presence, team decisions and approved content to create work that stays aligned."/>{q.isLoading?<LoadingState label="Loading brand memory"/>:q.isError?<ErrorState message={(q.error as Error).message} retry={()=>q.refetch()}/>:<><section className="panel form-panel"><div className="section-heading mt-0"><div><h2>Brand DNA</h2><p>What SMAA understands about your voice and identity.</p></div></div><div className="grid gap-8 md:grid-cols-2">{Object.entries({"Brand voice":q.data?.voice,"Audience":q.data?.audience,"Messaging":q.data?.messaging,"Visual identity":q.data?.visualIdentity}).map(([key,val])=><div key={key}><h3 className="text-sm font-semibold mb-3">{key}</h3>{val?.length?<div className="tag-list">{val.map(x=><span className="tag" key={x}>{x}</span>)}</div>:<p className="text-sm text-muted-foreground">No confirmed context yet.</p>}</div>)}</div></section><div className="section-heading"><div><h2>Knowledge sources</h2><p>Connected sources that shape your brand context.</p></div></div>{q.data?.sources?.length?<div className="integration-grid">{q.data.sources.map(s=><article className="panel integration-card" key={s.id}><span className="integration-icon">{s.name.slice(0,1)}</span><div><h3>{s.name}</h3><p>{s.connected?`Connected${s.count?` · ${s.count} analyzed`:""}`:"Not connected"}</p></div></article>)}</div>:<EmptyState title="No knowledge sources connected" message="Brand knowledge is ingested outside this build. Confirmed context appears here once a brand run has completed."/>}</>}</div>}

// No integrations API exists in this build, so the screen states that plainly instead of failing a request.
export function IntegrationsScreen(){return <div className="page-wrap"><PageHeader eyebrow="Connections" title="Integrations" description="Connections are managed outside this build. These are the channels the team works in — SMAA does not connect to them here."/><div className="integration-grid mt-5">{["Slack","Instagram","Website","LinkedIn","TikTok","YouTube","Facebook","X"].map(name=><article className="panel integration-card" key={name}><span className="integration-icon">{name[0]}</span><div><h3>{name}</h3><p>Not part of this build.</p></div></article>)}</div></div>}

// Publishing has no backend. Static, honest, and it points at the one place that does work.
export function PublishingScreen(){return <div className="page-wrap"><PageHeader eyebrow="Publishing" title="Publishing is not part of this build." description="Scheduling and distribution are out of scope here."/><EmptyState title="Publishing is not part of this build" message="Work you keep is written into the shared assets library. Open the Library to see everything SMAA has produced." action={<Button asChild variant="outline"><Link to="/library">Open library</Link></Button>}/></div>}

export function SettingsScreen(){return <div className="page-wrap"><PageHeader eyebrow="Workspace" title="Settings" description="Workspace settings are managed outside this build."/><div className="settings-list">{[["Profile","Managed outside this build"],["Workspace","Managed outside this build"],["Generation preferences","Defaults are set on the server"],["Notifications","Not part of this build"],["Integrations","Connections are managed outside this build"]].map(([a,b])=><div className="settings-row" key={a}><h3>{a}</h3><p>{b}</p></div>)}</div></div>}
